"""Read-only accepted720 review extraction. Stdlib only; never import model code.

Run with the bundled Python and -B. Writes only beside this script. The review
annotations below are deliberately explicit: AST/cache data cannot select the
live monkey-patched call graph by itself. A binding is never a dispatch receipt.
"""
from __future__ import annotations
import ast
import collections
import hashlib
import json
from pathlib import Path
import re
import subprocess
import sys

sys.stdout.reconfigure(encoding="utf-8")
OUT = Path(__file__).resolve().parent
PROJECT = Path(r"${WORKSPACE}\cyberpunk-b580-nr-opt")
BASE = PROJECT / "artifacts/b580-full-implementation-v1-20261003"
SOURCE = BASE / "phase2-complete/revisions/r18/source"
MANIFEST = BASE / "phase2-complete/PHASE2-r18.json"
RESULT = Path(r"${EXPERIMENTS_E}\cyberpunk-opt\b580-full-implementation-v1-20261003\luna\phase2\attempt-35-r18-e-vit-rowonce-p4\accepted_baseline\measurement\readonly\RESULT.json")
AMD = Path(r"${EXPERIMENTS_E}\cyberpunk-opt\amd-20261003-current720-reanalysis\upstream")
AMD_SHA = "9ec741522d267c4d2365af53081716fb2943068a"
EXPECTED_MANIFEST = "699ee05cf1008610a4772dfeebe6398d7099c7c1ed141cbbaa91967da0a05f7f"
EXPECTED_RESULT = "577bba204e365c93f6f61f3578362c73661fadc8902430bd6502bf01e3d9c781"
SCOPE = PROJECT / "artifacts/b580-full-coverage-audit-v2-20261003/RUNTIME_SCOPE_720.json"
BRIDGE_RECEIPT = Path(r"${EXPERIMENTS_D}\cyberpunk-opt\gpu-handoff-serial-owner-v2-20261002\source-integration-v2\MAIN_CANONICAL_SOURCE_RECEIPT.json")
BRIDGE = PROJECT / "artifacts/gpu-handoff-owner-transfer-v1-20261002/payload/native/nr_texture_bridge_re8_v1.cpp"
M = "experimental/fp8_unround_overlay/modules/"
B = "experimental/fp8_unround_overlay/nr_backend/"

def digest(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()

def read_json(path):
    return json.loads(Path(path).read_text(encoding="utf-8-sig"))

def write_json(name, value):
    (OUT / name).write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

def text(path):
    return Path(path).read_text(encoding="utf-8-sig")

def reference(file, symbol=None, line=None, root=SOURCE):
    path = root / file
    content = text(path)
    found = []
    if path.suffix == ".py" and symbol is not None:
        tree = ast.parse(content)
        def scan(node, prefix=""):
            for child in ast.iter_child_nodes(node):
                if isinstance(child, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)):
                    name = prefix + child.name
                    if name == symbol:
                        found.append(child)
                    scan(child, name + ".")
                else:
                    scan(child, prefix)
        scan(tree)
        if len(found) != 1:
            raise ValueError(f"Expected one definition: {file}::{symbol}, found {len(found)}")
        line = found[0].lineno
        end = found[0].end_lineno
    else:
        if line is None:
            hits = [i+1 for i, s in enumerate(content.splitlines()) if symbol in s]
            if not hits:
                raise ValueError(f"Missing anchor {file}::{symbol}")
            line = hits[0]
        end = line
    return dict(file=file, path=path.as_posix(), symbol=symbol, line=line, end_line=end,
                sha256=digest(path), link=f"{path.as_posix()}:{line}")

def amd(file, symbol, line=None, relation="analogous_compute"):
    r = reference(file, symbol, line, AMD)
    r.update(commit=AMD_SHA, relation=relation,
             url=f"https://github.com/lmxxf/dlss5-on-amd-9070xt-porting/blob/{AMD_SHA}/{file}#L{r['line']}")
    return r

# AMD references name a body when exports are generated by macros. They do not
# claim that every optional export was selected by the author's archived run.
A = {
    "prefix": amd("hip/wave_owned_c32.inc", "cw_body", 206, "one_AMD_body_to_many_local_ops"),
    "prefix_features": amd("hip/prefix_fast.hip", "dlss5_prefix_fast_features"),
    "c32": amd("hip/wave_owned_c32.inc", "cw_body", 206, "one_AMD_body_to_many_local_ops"),
    "c32_exports": amd("hip/wave_owned_c32.inc", "c32_wave1_chain", 532),
    "mh": amd("hip/wave_owned_mh.inc", "swin_wave2_body", 258, "one_AMD_body_to_many_local_ops"),
    "mh_qkv": amd("hip/wave_owned_mh.inc", "QKV_FUSE", 563),
    "c512_ffn": amd("hip/c512_m32_deep.inc", "split_ffn_one_w2f8", 242, "one_AMD_body_to_local_linear_expand_reduce; local_entry_project_remain"),
    "c512_tail": amd("hip/c512_qkv_attention_compact.inc", "c5c_body", 96, "one_AMD_body_to_GEMM_pack_attention"),
    "vit_qkv": amd("hip/vit_stream.inc", "vit_stream_qkv_frag_hin_w5f8", 152),
    "vit_contract": amd("hip/vit_stream.inc", "vit_stream_contract_frag_hout", 191),
    "vit_expand": amd("hip/deep_fast.hip", "vit_expand_blocked_body_m", 650),
    "vit_projection": amd("hip/vit_stream.inc", "vit_stream_project_tiles", 22),
    "vit_attn": amd("hip/deep_fast.hip", "vit_attention_transposed_score_body", 257, "400_640_selected_transposed_body_to_many_local_ops; 240_uses_256_export_fallback_body363"),
    "vit_pack": amd("Development/HIP/hip_reference_network.h", "Tensor Gather", 617),
    "decoder": amd("hip/deep_fast.hip", "void decoder_project2x_h16w", 462, "one_AMD_kernel_to_projection_and_gather"),
    "pool": amd("hip/multihead_fast.hip", "mh_pool_project_production", 200),
    "post": amd("hip/wave_owned_c32.inc", "c32_wave1_post", 537, "one_AMD_body_to_many_local_ops"),
    "post_rgb": amd("hip/boundary_fast.hip", "hip_post_head_fast_half", 13),
    "queue": amd("hip/swin_persistent.inc", "sp_run_body", 38),
    "history_absent": amd("src/native_pre_upscale.h", "reset", 220, "no_equivalent_real_motion_history_on_regular_route"),
    "bridge": amd("Development/HIP/hip_d3d12_bridge.h", "", 215, "interop_protocol_analogy_only"),
}

ROWS = []
def row(id, stage, file, symbol, callable, shape, math, rw, producer, consumer,
        amd_key, difference, opportunity="already", evidence="static", gate=None,
        binding=None, predicate=None, line=None, sites=None, kind="triton_kernel"):
    r = dict(id=id, stage=stage, kind=kind, local=reference(file, symbol, line),
             actual_callable=callable, shape_dtype_fullK=shape, arithmetic=math,
             reads_writes_layout_temporaries=rw, producer=producer, consumer=consumer,
             amd=[A[amd_key]] if amd_key else [], comparison=difference,
             improvement=opportunity, evidence_class=evidence, evidence_gate=gate,
             binding_symbol=binding or (symbol if kind == "triton_kernel" else None),
             binding_predicate=predicate or {}, sites=sites or [],
             dynamic_dispatch_trace=False, physical_memory_traffic_measured=False)
    ROWS.append(r)
    return r

def jit(id, stage, module, symbol, shape, math, rw, producer, consumer, a, diff,
        op="already", evidence="capture_route_static_kernel_resolution", gate=None, pred=None, sites=None):
    prefix = "game/" if (SOURCE / f"game/{module}.py").exists() else M
    return row(id,stage,prefix+module+".py",symbol,module+"."+symbol,shape,math,rw,producer,consumer,
               a,diff,op,evidence,gate,predicate=pred,sites=sites)

def ops(id, stage, file, symbol, callable, shape, math, rw, producer, consumer, a, diff,
        op="already", evidence="static_main_chain", line=None, sites=None, kind="torch_data_or_ALU"):
    return row(id,stage,file,symbol,callable,shape,math,rw,producer,consumer,a,diff,op,evidence,line=line,sites=sites,kind=kind)

# Source-defined sites, not a claim of measured physical dispatch counts.
SHIFTS = [(0,0),(4,4),(0,4),(4,0)]
SITES = []
def site(block, name, c, hw, shift=(0,0), role="body"):
    hp,wp = (hw[0]+(8 if shift[0] else 0),hw[1]+(8 if shift[1] else 0))
    SITES.append(dict(block=block,name=name,channels=c,valid_HWC=[*hw,c],
                      padded_HWC=[hp,wp,c],shift=list(shift),role=role))
site(0,"pre",32,(768,1280),role="prefix")
for start,count,c,hw in [(1,4,32,(384,640)),(5,4,64,(192,320)),(9,6,128,(96,160)),(15,8,256,(48,80))]:
    for i in range(count): site(start+i,f"encoder{c}.{i}",c,hw,SHIFTS[i%4],"down_tail" if i==count-1 else "body")
for side,start in [("encoder",23),("decoder",40)]:
    for i in range(8):site(start+i,f"{side}512.{i}",512,(24,40),SHIFTS[i%4],"head_tail" if start==23 and i==7 else "body")
for i in range(8):site(31+i,f"vit.{i}",1024,(12,20),role="full240tokens")
site(39,"decoder_input",512,(24,40),role="transition")
for start,count,c,hw,offset in [(48,8,256,(48,80),0),(56,6,128,(96,160),2),(62,4,64,(192,320),0),(66,4,32,(384,640),0)]:
    for i in range(count): site(start+i,f"decoder{c}.{i}",c,hw,SHIFTS[(i+offset)%4],"up_body" if i==0 else "body")
site(70,"post",32,(768,1280),(4,4),"post")
SITES.sort(key=lambda x:x["block"])
def family(c):return [s["name"] for s in SITES if s["channels"]==c and s["role"] not in ("prefix","post","transition")]

# Front / actual fractional temporal route / unobserved accepted conditional route.
for suffix,shape in [("reset","TEMPORAL=false，seed 0"),("history","TEMPORAL=true，seed 1…12")]:
    jit("F-"+suffix,"front","front_noise_native_720_kernel_v1","front",
        "RGB f32[720,1280,3]→f16[768,1280,16]；B128，4warps；"+shape+"；HISTORY_COMPONENTS=false",
        "标量 native radius+trig；反射边界/控制10…14；half 发布，无新增FP8",
        "读RGB及normalized history/reciprocal；写16-lane front 31,457,280B；融合noise，无逐lane临时",
        "RGB / H-normalized","pre K16", "prefix_features",
        "AMD prefix可连K16投影/整窗；regular重置输入不等价真实时序", "gap-front-fusion",
        "runtime_hash_and_calls",pred={"TEMPORAL":suffix=="history","HISTORY_COMPONENTS":False})
jit("H-axes","history","history_numeric_suite_720_v1_kernel","_prepare_axes",
    "motion f32[720,1280,2]；BLOCK128；10-plane f32 axes，NATIVE=false/DIRECT=false",
    "标量坐标/权重+reciprocal table，full five-tap轴系数",
    "读motion/table/维度倒数；写axes 36,864,000B +invalid 3,686,400B（每历史帧）",
    "实际运动及private previous","H-sample","history_absent","AMD regular无相同运动warp；不得以去掉history换收益",
    "already","runtime_hash_and_calls",pred={"NATIVE":False,"DIRECT":False})
jit("H-sample","history","history_numeric_suite_720_v1_kernel","_five_tap",
    "previous f16 HWC3；VALUE_FP32=true；BLOCK64，4warps；DEBUG=false/WRITE_NORMALIZED=true",
    "5个bilinear tap每tap4texel；FP32 fractional值混合，原half坐标/标量table边界",
    "读axes/previous/table；写numerator11,059,200B、reciprocal3,686,400B、normalized11,059,200B、invalid3,686,400B；非DEBUG无TAPS存储",
    "H-axes","F-history及post temporal blend","history_absent",
    "已融合5tap；normalized虽然不返回仍写；tap逻辑计数60不是60个核",
    "gap-history-output","runtime_hash_and_calls",pred={"DEBUG":False,"VALUE_FP32":True})
ops("H-route","history","game/history_numeric_suite_720_v1.py","HistoryNumericCounter720.__call__",
    "motion.half().float() / round / sub / abs / le / all / bool",
    "HWC2 1,843,200元素→host bool；fixed13 12 fractional /0 near", "标量/通用reduction，无DPAS",
    "数次全motion遍历和bool同步；具体ATen物理核未知", "motion","H-axes或H-near",None,
    "AMD没有对应路线；不能因bool同步忽略真实motion predicate", "gap-summary")
ops("H-near","history",B+"sampling.py","warp_history_normalized",
    "owned near_warp→_axis_weights→_sample_five_axes→_half_texture_counts / NativeReciprocalTable.forward",
    "720×1280，near-integer predicate；5tap/full image", "half纹理计数及FP32 table；fp32_fractional不把near改为fp32_all",
    "torch meshgrid/half/floor/索引/权重/5sample/表查/分组及total；详见附录AST逐调用点",
    "H-route","F-history / post",None,"仍为可达accepted路径，但fixed13近整数0；非新pixel_rgb/fused_near",
    "already","conditional_unobserved")
ops("H-tables","history",B+"reciprocal.py","NativeDimensionReciprocalTable.forward",
    "dimension table indexed view / cached scalar arguments", "W1280/H720 f32标量", "仅查表/metadata，非独立矩阵",
    "读常量，返回标量view；dimension.width/height各12为逻辑调用，非24物理核", "常量","H-axes/H-sample",None,
    "AMD可原生倒数；保留table不等于需要另起矩阵核")

# Pre and C32: pre/post/ordinary/decoder66 are distinct consumer chains.
jit("P-k16","pre","native_k8_fp16_v1","_native_k8_fp16",
    "M983040 K16 N32；BM/BN/BK32，4warps；f16", "FP16 tl.dot→f32 accumulator→half；K16完整（文件名K8不是有效K）",
    "front HWC16读一次到tile；写HWC32 62,914,560B", "F-reset/history","P-mlp","prefix",
    "native前投影已实现；AMD inline prefix消除该HWC32中间", "gap-front-fusion",gate="native_k8_pre_post")
for id,stage,sites,shape,consumer,akey in [
    ("P-mlp","pre",["pre"],"M983040", "P-qkv","prefix"),
    ("S32-mlp","C32",family(32),"M245760/254016/248832/250880", "S32-qkv或D32-qkv","c32"),
    ("O-mlp","post",["post"],"M999488=776×1288", "O-qkv","post")]:
    jit(id,stage,"native_cubic_c32_v1","_kernel",shape+" C32→128→32；BM32，4warps，ROUND_ACTIVATION=false",
        "FP16 DPAS候选；4×K32 hidden片顺序累计，cubic native half，half residual/store",
        "读X/Wexp/Wcontract/skip；hidden保留寄存器，写MLP HWC32；无需重做hidden fusion",
        "P-k16 / padded C32 / O-entry",consumer,akey,
        "已融合exp+cubic+contract；AMD继续在同窗做QKV/tail，避免MLP落地", "N3" if stage=="C32" else "gap-front-fusion",
        gate="c32_hidden_native_ten",sites=sites)
for id,stage,shape,prod,cons,akey,sites in [
    ("P-qkv","pre","768×1280", "P-mlp","P-tail","prefix",["pre"]),
    ("S32-qkv","C32","384/392×640/648","S32-mlp","S32-tail","c32",family(32)),
    ("D32-qkv","decoder32","384×640","D32-mlp","D32-attn","c32",["decoder32.0"]),
    ("O-qkv","post","776×1288","O-mlp","O-tail","post",["post"])]:
    jit(id,stage,"fused_c32_projection_native_half_v1","_kernel",shape+" C32，BM32/4warps；grid(rowtile,3)，fullK32",
        "每Q/K/V独立tl.dot FP16→f32→half；Q/K native half norm/scale，unround",
        "读MLP/W/order/scale；3个packed[windows,64,32]half，写3×M×32×2B",
        prod,cons,akey,"已直接pack，无raster QKV中间；AMD一窗保有MLP与QKV", "N3" if stage=="C32" else "already",sites=sites)
for id,stage,shape,prod,akey,sites in [
    ("P-tail","pre","768×1280", "P-qkv","prefix",["pre"]),
    ("S32-tail","C32","384×640；4shift","S32-qkv","c32",[s for s in family(32) if s!="decoder32.0"]),
    ("O-tail","post","768×1280；shift4,4","O-qkv","post",["post"])]:
    jit(id,stage,"post_attention_fusion_v1","_attention_project",shape+"；2query tiles/window×32q，full64 keys，C32",
        "QK/AV/projection FP16 tl.dot→f32；exp/denominator half，unrounded probabilities；half残差",
        "读QKV/bias/Wproj/MLP；score/exp/AV寄存器；写有效HWC32，已融合crop/residual",
        prod,"下一块/pool/post head",akey,"attention+projection已经融合；AMD优势在继续闭合前段", "N3" if stage=="C32" else "already",sites=sites)
jit("D32-attn","decoder32","fused_swin_core_native_half_v1","_kernel",
    "windows3840×64×32；BM32，4warps，ROUND_WEIGHTS=false；full64key",
    "FP16 QK/AV +half exp/denominator；无FP8 probability", "QKV→packed attended half；score局部，无global score",
    "D32-qkv","D32-unpack","c32","block66经DecoderGather专路，不是ordinary7融合tail", "N3",sites=["decoder32.0"])
jit("D32-unpack","decoder32","window_layout_v1","_unpack","384×640 C32；BLOCK256，inverse order",
    "纯数据搬运/布局，非DPAS", "packed attended读一写一→HWC32 15,728,640B",
    "D32-attn","D32-project","c32","block66还有显式unpack；AMD up-body闭合", "N3",sites=["decoder32.0"])
jit("D32-project","decoder32","fast_matrices_v3","_matmul","M245760 K32 N32 INITIALIZED=true；BM16 BN32 BK32，4warps",
    "FP16 tl.dot→f32+half initial→half", "读attended/W/half initial；写HWC32；skip multiply另列",
    "D32-unpack / D32-skip","post input","c32","此支有独立projection；不要把post融合误贴block66", "N3",pred={"M":245760,"K":32,"N":32},sites=["decoder32.0"])
ops("D32-skip","decoder32",M+"decoder_gather_scope_v1.py","DecoderGather.upsample","(mlp*skip_scale).half()",
    "384×640×32 f16", "标量乘+half初值", "写initial15,728,640B→D32-project", "D32-mlp","D32-project","c32","AMD窗内保有残差", "N3",sites=["decoder32.0"])
ops("S32-pad","C32","game/c32_repeated_tail_fusion_v1.py","fused_forward_unquantized","torch.nn.functional.pad / crop views",
    "384×640→392×648/384×648/392×640；4shift", "零扩展非cyclic roll；pure data",
    "非零shift读有效X写完整padded X；crop为view/或tail地址处理", "前块","S32-mlp","c32","AMD映射输入避免padded global surface", "N3",sites=family(32))

# Three multihead families, not one generic Swin row.
for c,hw,bm,bs in [(64,"192/200×320/328",32,2),(128,"96/104×160/168",32,4),(256,"48/56×80/88",16,8)]:
    st=f"C{c}"; ss=family(c)
    mod="branched_mlp_pairwise_720_v1" if c==128 else "batched_branched_mlp_v1"
    fun="_pairs_pairwise" if c==128 else "_pairs"
    jit(st+"-pairs",st,mod,fun,f"{hw} C{c}；{bs} branches C→128→32；BM{bm}/4warps；fullK{c}/K128",
        "FP16 tl.dot，K32片；native cubic half（表/实现按callee），reduce half，ROUND_REDUCED=false",
        f"读padded X与branch W；hidden寄存器；写half latent[{bs},M,32]（总M×C×2B）",
        st+"-pad",st+"-mlpproject","mh","C128 pairwise已开；AMD QT4共享W并接QKV/tail", "N5",gate="c128_pairwise_twelve" if c==128 else f"c{c}_all_"+("eight" if c==64 else "sixteen"),pred={"C":c},sites=ss)
    pmod,pfun=("branch_accum_native_720_kernel_v1","_project_fp32") if c==128 else ("batched_branched_mlp_v1","_project")
    jit(st+"-mlpproject",st,pmod,pfun,f"{hw} C{c}；BM16 BN64，4warps；{bs} full K32 branches",
        "C128已FP32跨branch累积→half" if c==128 else "每branch FP16 dot→FP32加上一half结果→half；顺序边界",
        f"读latent/Wproj/X/skip；写MLP HWC{c}；BN64分列重复读latent，次数C/64",
        st+"-pairs",st+"-qkv","mh","C128 native branch累积已实现；C64/256旧half边界可fast数学后续",
        "N5","runtime_hash_and_calls" if c==128 else "capture_route_static_kernel_resolution",
        pred={"C":c},sites=ss)
    qmod={64:"c64_qkv_direct_pack_v2",128:"c128_qkv_direct_pack_one_v1",256:"c256_qkv_direct_pack_one_v1"}[c]
    qfun="_qkv_direct_pack" if c==64 else "_direct_pack"
    jit(st+"-qkv",st,qmod,qfun,f"{hw} C{c}；head{bs}，32channels/head；BM"+("32" if c==256 else "16")+" BN32 BK32，4warps；fullK"+str(c),
        "FP16 DPAS目标；Q/K half norm+scale，Vhalf；ROUND_QKV=false",
        f"head×Q/K/V grid独立重复读A；直接写3×head×windows×64×32 half，没有raster QKV中间",
        st+"-mlpproject",st+"-tail" if c!=256 else "C256-attn","mh_qkv",
        "直接pack已开；AMD C64/128 QKV_FUSE共读A，C256结构不同", "N4" if c!=256 else "N6",sites=ss)
    if c!=256:
        jit(st+"-tail",st,f"c{c}_attention_project_fused_720_v1","_fused",
            f"{hw} C{c}；BM"+("32" if c==64 else "16")+f"，4warps；{bs}heads，全64keys，全K{c} projection",
            "QK/AV/跨head projection FP16 DPAS→f32；half exp/denom/attended/residual",
            "读packed QKV/BIAS/W/MLP；score/AV局部；直接写valid HWC，已免unpack及attended落地",
            st+"-qkv","下一块/pool","mh","现役已经融合attention/projection/crop；不能重复计此收益",
            "N4",gate=f"c{c}_attention_project_"+("eight" if c==64 else "twelve"),sites=ss)
    ops(st+"-pad",st,B+"multihead_block.py","MultiHeadSwinBlock.forward_unquantized","torch.nn.functional.pad",
        f"{hw} C{c}；shift0/4，每边对8齐", "pure data，unround family边界返回原half",
        "写padded HWC；后续全部MLP会处理padding；AMD mapped input与pad-attention需分开", "前块/gather",st+"-pairs","mh",
        "替换padding只省搬运不能自动删attention full64keys；编码tail仍需pool", "N4" if c!=256 else "N6",sites=ss)
jit("C256-attn","C256","window_block_attention_v3","_kernel",
    "8heads；60/77/66/70 windows/head；BM32 4warps；full64 keys，ROUND_WEIGHTS=false",
    "FP16 QK/AV；half exp/denom/attended", "读QKV/bias；写packed AV[M,256]half；score不落地",
    "C256-qkv","C256-project","mh","此家族尚分attention/projection；AMD wave tail或persistent queue", "N6",sites=family(256))
jit("C256-project","C256","window_block_projection_v3","_project",
    "48×80输出；HP48/56 WP80/88；BM16 BN32 4warps；fullK256",
    "FP16 dot→f32+half residual→half", "读packed AV/MLP/W；每列tile8份输入请求，写有效HWC256；crop在地址中",
    "C256-attn","后续块/pool/gather","mh","packed projection/crop已开；队列/共享producer收益待测", "N6",sites=family(256))

# Pooling and down projections: explicit ATen half operations are not free views.
for id,file,symbol,c,hw,n,a in [
    ("P-pool",B+"pre_block.py","PreBlock.forward_features_outputs",32,"768×1280",32,"prefix"),
    ("C32-pool",B+"c32_block.py","C32SwinBlock.forward_outputs",32,"384×640",64,"c32"),
    ("C64-pool",B+"multihead_block.py","MultiHeadSwinBlock.forward_outputs",64,"192×320",128,"pool"),
    ("C128-pool",B+"multihead_block.py","MultiHeadSwinBlock.forward_outputs",128,"96×160",256,"pool"),
    ("C256-pool",B+"multihead_block.py","MultiHeadSwinBlock.forward_outputs",256,"48×80",512,"pool"),
    ("C512-pool","game/fullsize_session_v1.py","FullsizeSession.__init__.c512",512,"24×40",1024,"pool")]:
    ops(id,"pool",file,symbol,"slice views + top add.half + bottom add.half + sum.half + mul(.25).half + alignment pad",
        f"unquantized {hw} C{c}→half spatial/2；C{n}下一投影", "标量half边界；不得从量化skip重新pool",
        "slice本身view；top/bottom/sum/scaled为数据输出，具体ATen合并未知；最终pool落地", "对应tail","down projection / encoder next stage",a,
        "AMD finish或pool_project就地消费；现役尾部fusion没有吞掉这些ATen操作", "N3" if c==32 and id!="P-pool" else "gap-pool-fusion")
    if id!="P-pool":
        mm={32:61440,64:15360,128:3840,256:960,512:240}[c]
        jit(id+"-dot","pool","fast_matrices_v3","_matmul",f"M{mm} K{c} N{n}；BM16 BN32 BK32，4warps",
            "FP16 tl.dot→f32→half；完整K", "读pooled half/W；写down HWC；pad对4齐均能是0但源调用仍列明",
            id,"下一编码层或ViT","pool","AMD pool+project融合；不是现役已有全模块融合", "gap-pool-fusion",pred={"M":mm,"K":c,"N":n})

# C512 valid FFN / padded full-key attention / encoder and decoder divergence.
for fun,desc,k,prod,cons,rw in [
    ("_entry","逐行absmax/scale/quant",512,"C512 block input","C512-linear","Xhalf→QX i8[960,512] +SX f32[960]"),
    ("_linear","INT8 linear",512,"QX/SX","C512-expand","QX+W[N,K] i8→QZ i8[960,512]；scale/half再量化"),
    ("_expand","8group expand+cubic",64,"QZ","C512-reduce","QZ→QH i8[960,2048]；8group×256hidden；native half cubic"),
    ("_reduce","8group reduce",256,"QH","C512-project","QH→QG i8[960,512]；8group×64output"),
    ("_project","INT8 final+residual",512,"QG/X","C512-pad","QG/W/skip→MLP half[960,512]；半精度initial再加")]:
    jit("C512-"+fun[1:],"C512","c512_int8_ffn_rows_v1",fun,
        f"M960 valid24×40；fullK{k}；BM32 BN64，4warps/1stage" if fun!="_entry" else "M960，C512，一program/row，4warps",
        "标量quantizer" if fun=="_entry" else "tl.dot i8*i8→i32，DPAS目标；f32 scale，half activation/residual边界",
        rw+"；DEBUG=false；OUT/ENTRY ROUND_FP8=false",prod,cons,"c512_ffn",
        desc+"已为完整INT8矩阵，非FP16模拟；AMD FP8 WMMA分组融合省QH中间", "gap-c512-groups",sites=family(512))
ops("C512-pad","C512","game/fullsize_session_v1.py","FullsizeSession.__init__.c512","torch.nn.functional.pad",
    "MLP24×40×512→24×40/32×48/24×48/32×40", "pure zero extension；full64key不变",
    "有效960行变960/1536/1152/1280；16站共19712 padded rows", "C512-project","C512-QKV","c512_tail",
    "AMD validraster访问QKV；删无效QKV行需要attention保持补0/fullK", "N1",sites=family(512))
ops("C512-QKV","C512","game/c512_qkv_library_16_v1.py","installed.dense","torch.mm(features.reshape(-1,512), weight[512,1536])",
    "M960/1536/1152/1280 K512 N1536；f16，fullK；16sites", "XPU library GEMM；API f16→f16，内部accum/tile/ISA未知",
    "读padded MLP/W，写z[M,16,3,32]half；约60,555,264B/整帧 QKV output",
    "C512-pad","C512-pack","c512_tail","库QKV拼3已经实现；AMD紧凑QKV+attention不落z",
    "N1","capture_provider_calls_library_internals_unknown",sites=family(512),kind="library_GEMM")
jit("C512-pack","C512","fused_qkv_pack_native_half_v1","_pack",
    "16heads×15/24/18/20windows；BR16，4warps；fullhead32",
    "half norm/scale；ROUND_QKV=false；pure vector math+pack非矩阵",
    "读raster z；写Q/K/V head/window/order packed half，总3×M×512×2B",
    "C512-QKV","C512-attn","c512_tail","现役已norm+pack一核；AMD该边界与QKV/attention闭合", "N1",sites=family(512))
jit("C512-attn","C512","c512_probability_unround_kernel_v1","_kernel",
    "16heads，15/24/18/20windows/head；BM32，4warps；full64 keys",
    "FP16 DPAS QK/AV→f32；half exp/denom/AV，ROUND_WEIGHTS=false",
    "score在寄存器；写packed attended[M,512]half；producer for encoder unpack/decoder packed proj",
    "C512-pack","C512-E-unpack / C512-D-proj","c512_tail","probability unround及full64key已在现役；AMDQKV与deep4ring就地feed", "N1",gate="c512_probability_all_sixteen",sites=family(512))
jit("C512-E-unpack","C512-encoder","window_layout_v1","_unpack",
    "valid24×40及3种padding，heads16；TOTAL491520/786432/589824/655360，BLOCK256",
    "纯数据/逆pixel_order", "读packed AV写padded raster HWC512→crop view，crop后contiguous可能复制",
    "C512-attn","C512-E-proj","c512_tail","encoder仍raster projection，decoder已直接packed消费；两路不能混同", "N1",pred={"HEADS":16},sites=[f"encoder512.{i}" for i in range(8)])
ops("C512-E-initial","C512-encoder",B+"split_block.py","SplitProjection.forward_unquantized","(q(residual)*skip_scale).half() / crop.contiguous in dot",
    "valid24×40×512 half", "标量half残差；q在unround下identity", "写half initial983040B；shift crop noncontiguous可能读写attended983040B",
    "C512-project / C512-E-unpack","C512-E-proj","c512_tail","AMD窗内保有残差并mapped projection", "N1")
jit("C512-E-proj","C512-encoder","fast_matrices_v3","_matmul","M960 K512 N512 initialized=true；BM16 BN32 BK32，4warps",
    "FP16 dot→f32+half initial→half；fullK512", "读validraster AV/W/initial，写full[24,40,512]half",
    "C512-E-unpack / C512-E-initial","下一block或C512-pool","c512_tail","编码投影与decoder packed consumer不同", "N1",pred={"M":960,"K":512,"N":512},sites=[f"encoder512.{i}" for i in range(8)])
jit("C512-D-proj","C512-decoder","c512_window_projection_v1","_project",
    "24×40 output；HP24/32 WP40/48；BM16 BN32，4warps；fullK512",
    "FP16 dot→f32+half residual→half", "读packed attended及validMLP，写validHWC512；已经免unpack/crop临时",
    "C512-attn / C512-project","下一decoder或D256 input","c512_tail","decoder已有packed→raster投影；不能再声称同边界新增收益", "N1",sites=[f"decoder512.{i}" for i in range(8)])

# ViT full 240 tokens and full K, including two GEMMs and P4 half boundaries.
for fun,shape,prod,cons,math,rw in [
    ("_entry","240×1024，一program/row","ViT input","V-expand","absmax scale+标量INT8 quant","写QX245760B/SX960B"),
    ("_expand","M240 K1024 N4096，BM32 BN32","V-entry","V-contract","i8*i8→i32 DPAS；f32 scale→half→native cubic→quant","读QX/SX及Wout-major；写QH983040B"),
    ("_contract","M240 fullK4096 N1024 PARTS4，BM32 BN32","V-expand","V-merge","4个完整K1024 i32 partition；总fullK4096","写partial[4,240,1024]i32 3,932,160B，无half partition"),
    ("_merge","M240 N1024，B512","V-contract","V-qkv","四i32相加→scale+half initial→half","读partial4份、X/scale/skip；写MLP491520B")]:
    jit("V-"+fun[1:],"ViT-FFN","int8_ffn_segment_rows_v1",fun,shape+"，4warps/1stage；DEBUG=false",
        math,rw,prod,cons,"vit_expand" if fun in ("_entry","_expand") else "vit_contract",
        "现役已INT8矩阵+行量化一次+完整tokens；r18 audit候选K64变化不属于此baseline", "already",sites=[f"vit.{i}" for i in range(8)])
jit("V-qkv","ViT-attention","fast_matrices_v3","_matmul",
    "两次 M240 K512 N3072（总fullK1024），BM16 BN32 BK32，4warps，FP16",
    "每K512 GEMM f32累积→half；两half输出add→half另列",
    "两个MLP半列view→contiguous copy；两个QKVhalf临时各1,474,560B；写合并z同尺寸",
    "V-merge","V-qkv-add","vit_qkv","AMD全K融合QKV+norm发布head-major；保两K512仅用于结构收益隔离", "N2",pred={"M":240,"N":3072,"K":512},sites=[f"vit.{i}" for i in range(8)])
ops("V-qkv-add","ViT-attention","game/fullsize_session_v1.py","FullsizeSession.__init__.vforward",
    "(GEMM0+GEMM1).half().reshape(240,32,3,32)", "z FP16[240,32,3,32]；fullK1024总和",
    "标量half add边界，reshape通常view", "读2份half，写z1,474,560B；不可把reshape算必有核", "V-qkv","V-norm-Q/K/V","vit_qkv",
    "AMD不需两个输出与add；fast版允许随后fullK单累积", "N2")
for q in ("Q","K"):
    row("V-norm-"+q,"ViT-attention",B+"triton_attention_normalize.py","_normalize","nr_backend.triton_attention_normalize._normalize",
        "7680 rows×32 f16，BR16/4warps", "native顺序half norm/FMA补偿 helper，最终half",
        "读z strided Q/K（wrapper contiguous）；写normalized491520B/种", "V-qkv-add","Qscale / V-QK","vit_qkv",
        "AMDQKV末端寄存器norm；现役独立norm，原生fast norm可后续", "N2","capture_route_static_kernel_resolution")
ops("V-Qscale","ViT-attention","game/fullsize_session_v1.py","FullsizeSession.__init__.vforward",
    "(Qnorm*5.65625).half()*query_scale / half q / head transpose",
    "240×32×32 half；scale32heads", "两次half边界；transpose为view，值转换按dtype才有搬运",
    "读Qnorm/scale，写Q；Knorm/V切片及头布局是否拷贝见wrapper AST", "V-norm-Q/K","V-QK","vit_qkv",
    "head-major producer可直接供stream attention；不需新FP8舍入", "N2")
ops("V-pad-KV","ViT-attention",B+"vit_block.py","vit_attention","pad(key/value, 240→256 keys)",
    "32heads×256×32 half，16zero keys", "纯数据；完整240真实key+16pad",
    "读strided K/V写padded各524288B；pad贡献exp(0)用于旧denom补偿", "V-norm-K / zV","V-QK / V-AV","vit_attn",
    "流式核可mask padding但保初始隔离half denom；随后可原生denom", "N2")
jit("V-QK","ViT-attention","strided_batched_v1","_matmul",
    "batch32 M240 N256 fullK32，BM16 BN32 BK32 4warps",
    "FP16 DPAS dot→f32→half scores", "按Q/K stride读，不强制Qcopy；写scores[32,240,256]half3,932,160B",
    "Qscale / V-pad-KV","V-exp","vit_attn","AMD按keytile就地消费score；strided输入优化已有", "N2")
row("V-exp","ViT-attention",B+"triton_attention_exp.py","_kernel","nr_backend.triton_attention_exp._kernel",
     "N1966080 half scores；VIT=true B512；另N1 exp(0)每block", "标量特殊half exponent，非softmax通用exp",
    "读scores，写e3,932,160B；N1scalar用于padding correction", "V-QK","V-AV/V-denom","vit_attn",
    "AMD融合exp/AV/denom，原生exponent后续仍需质量验证", "N2","capture_route_static_kernel_resolution")
jit("V-AV","ViT-attention","fast_matrices_v3","_matmul",
    "batch32 M240 N32 fullK256，BM16 BN32 BK32，4warps",
    "FP16 probability (unround e)×V→f32→half numerator", "读e/padded V（contiguous wrapper可能copy），写[32,240,32]half491520B",
    "V-exp/V-pad-KV","V-final-div","vit_attn","AMDstream按64keytile累积分子，无e全局store", "N2",pred={"BATCHED":True,"N":32,"K":256})
row("V-denom","ViT-attention",B+"triton_attention_weights.py","_weights","nr_backend.triton_attention_weights._weights",
    "ROWS7680 BR32，NORMALIZE=false；4个64keychunk/ViT block", "有序half row_sum64；非FP32softmax sum",
    "wrapper将4个e[...,start:start+64]非连续view contiguous；每chunk读491520×2B，写7680half15360B",
    "V-exp","V-denom-merge","vit_attn","4chunk是4次调用；逻辑captured计数32不等同4×8物理全部eventtrace",
    "N2","capture_route_static_kernel_resolution")
ops("V-denom-merge","ViT-attention",B+"vit_block.py","vit_attention",
    "three add.half / exp(0)*padding.float().half / sub.half / clamp.float.reciprocal.half",
    "32×240×1；pad16", "原ordered half denominator+padding correction；fullK240",
    "row sum小临时多次写读；N1 exp-zero也是实际原路径，非候选constant shortcut",
    "V-denom / V-exp N1","V-final-div","vit_attn","AMD在线denominator；fullK新数学允许通过后替换", "N2")
ops("V-final-div","ViT-attention",B+"vit_block.py","vit_attention",
    "(numerator*reciprocal).half / transpose(0,1).reshape(240,1024) / (MLP*attn_skip).half",
    "attended240×1024 f16；skip initial同shape", "乘half；transpose为view但reshape可能copy；half residual initial",
    "写attended/initial各491520B；未由事件确认各copy的内部核数", "V-AV / V-denom-merge","V-proj-parts","vit_attn",
    "AMDhead-major尾部至projection；native fullK projection为数值候选，非必须永守P4", "N2")
for fun,rw,cons in [("_parts","写partial[4,240,1024]half1,966,080B；part0含halfinitial","V-proj-merge"),
                    ("_merge","读4个halfpartition，有序half归并，写output491520B","下一ViT/decoder")]:
    jit("V-proj-"+fun[1:],"ViT-projection","fused_vit_projection_v2",fun,
        "M240 fullK1024 N1024 PARTS4，BM32 BN64（parts）；merge B512，4warps",
        "FP16 DPAS→f32，K256 partition各half；part0 initial，merge sequential half" if fun=="_parts" else "标量有序half add，非DPAS",
         rw,"V-final-div" if fun=="_parts" else "V-proj-parts",cons,"vit_projection",
        "P4分区是一个grid带part维，不是4个launch；现役已两核projection", "N2",sites=[f"vit.{i}" for i in range(8)])

# Five decoder transition projections and five fused nearest gathers.
ops("D512-zero","decoder",M+"decoder_gather_scope_v1.py","DecoderGather.input","torch.zeros([12,20,512])",
    "initial half[240,512]", "填0纯数据/库allocation", "写245760B；用于第一K256partition initial", "ViT output","D512-proj", "decoder","AMDprojection通常寄存器0初值", "gap-decoder-fusion")
jit("D512-proj","decoder","fast_matrices_v3","_matmul",
    "4次M240 K256 N512（总fullK1024）；第一initialized=true其他false；BM16 BN32 BK32，4warps",
    "每K256独立FP32→half，随后3次有序half add；decoder模块持原split_k_projection别名",
    "写4个projected half[240,512]，3个merged half；ViT _parts/_merge不拥有decoder weight",
    "ViT output/D512-zero","D512-half-merge","decoder","AMD decoder_project2x融合fullprojection+upmerge；不能把D512说成ViT两核projection", "gap-decoder-fusion",pred={"M":240,"K":256,"N":512},sites=["decoder_input"])
ops("D512-half-merge","decoder",B+"vit_block.py","split_k_projection","3×(result+partition).half()",
    "240×512 half；fullK1024总和", "有序half，数值改变另验收", "读previous +partition→half[240,512]，3次", "D512-proj","D512-gather","decoder",
    "fast版已存在decoder_input_full_k候选但accepted=false", "gap-decoder-fusion")
for c,mm,hh,ww in [(512,240,24,40),(256,960,48,80),(128,3840,96,160),(64,15360,192,320),(32,61440,384,640)]:
    if c!=512:
        jit(f"D{c}-proj",f"decoder{c}","fast_matrices_v3","_matmul",f"M{mm} fullK{2*c} N{c}；BM16 BN32 BK32，4warps",
            "FP16 DPAS→f32→half", f"读low half/W；写低分辨率projected[{hh//2},{ww//2},{c}]half",
            "前decoder family",f"D{c}-gather","decoder","projection仍独立；gather融合已经存在", "gap-decoder-fusion",pred={"M":mm,"K":2*c,"N":c})
    jit(f"D{c}-gather",f"decoder{c}","decoder_gather_merge_v1","_raw_padded" if c==32 else "_quantized",
        f"target {hh}×{ww}×{c} half；B256/4warps；stridedprojected/skip；"+("rawC32" if c==32 else "ROUND_OUTPUT=true"),
        "nearest gather +补偿half FMA；C512/256/128/64保留现役merge E4M3 lattice，未追加新规则" if c!=32 else "nearest gather+补偿half FMA，保留rawC32 residual",
        f"读低projected按2×gather/skip/scale，写merged有效HWC{c}；没有repeat_interleave中间",
        f"D{c}-proj", "C512-entry" if c==512 else f"C{c}-pad/pairs" if c!=32 else "D32-mlp", "decoder",
        "all6 decoder_gather_unround去入口舍入，merge输出舍入另开关默认false；不得把未采用merge_unround当现役",
        "gap-decoder-fusion",pred={"C":c})
# Alias for decoder32 MLP is the same accepted native C32 kernel.
jit("D32-mlp","decoder32","native_cubic_c32_v1","_kernel","M245760 C32→128→32，BM32/4warps，unrounded hidden",
    "FP16 dot+cubic/residual half", "merged rawC32读→MLP half写；与ordinary7入口不同",
    "D32-gather","D32-qkv","c32","已包含S32-mlp同callable；单列block66链防遗漏", "N3",sites=["decoder32.0"])

# Post entry and real temporal output. No new audit FDP candidate in baseline.
jit("O-entry","post","post_entry_mlp_fusion_v1","_entry_kernel",
    "low384×640×32，skip768×1280×32→padded776×1288×32；BM32/4warps，ROUND_INPUT=false",
    "标量low scale half +skip补偿halfFMA，zero extension",
    "写raw merged63,967,232B；nearest无需expanded中间", "decoder32 output / pre_skip","O-mlp","post",
    "已融合up/merge/pad；AMDpost还含MLP/QKV/tail/head；FDP candidate不是本baseline", "gap-post-fusion",gate="post_entry")
jit("O-head","post","native_k8_active_720_v1","_post_half_dot",
    "M921600，W[32,8]，只写4channels RGB+logit；BM32/4warps；fullK32，一次tl.dot，BN16 masked N8",
    "FP16矩阵输入→FP32 DPAS累加→最终half；native_k8名称不表示分四个K8累加", "读HWC32与headW，写720×1280×4 half7,372,800B",
    "O-tail","O-base / O-sigmoid","post","native post K8已开；AMD头与post合一但只3RGB，不能删logit历史blend", "gap-post-fusion",gate="native_k8_pre_post")
ops("O-base","post",B+"post.py","ResetPostBlock.forward","head[:3].float / rgb.half.float / scalar gain-center / clamp",
    "720×1280×3 f32；gain1/32及baseRGB", "标量FP32，纹理RGB半精度边界",
    "读head/RGB，多次临时value；reset可clamp输出，history分支还blend", "O-head / RGB","O-blend/store","post_rgb",
    "AMDhead做RGB就地epilogue；FDP的1.80ms整段证据只可作为已有候选证据，不分摊本行", "gap-post-fusion")
ops("O-sigmoid","post",B+"sigmoid.py","NativeSigmoidTable.forward","logit.half.contiguous.view(i16).int &65535 / table[bits.long()]",
    "H×W logit，65536 f32 table；alpha H×W f32", "标量索引/查表，非DPAS",
    "logit contiguous、i32/i64 bits数组、table gather及scale/clamp；内部ATen核数未知",
    "O-head logit","O-blend",None,"AMDregular reset缺logit时序等价；native sigmoid为现有未选数值候选", "gap-post-fusion")
ops("O-blend","post",B+"post.py","ResetPostBlock.forward","fma32(previous,reciprocal,-value) / fma32(delta,alpha,value)",
    "720×1280×3 f32 numerator +H×W rcp；真实历史", "补偿FP32 FMA；完整motion/history，不从上一输出替代当前网络",
    "读numerator/rcp/alpha/value；delta/value临时f32；不得只用normalized重新round替换", "H-sample/O-base/O-sigmoid","O-store",None,
    "AMDregular无同配方；不可照搬只RGB epilogue", "gap-post-fusion")
ops("O-store","post",B+"post.py","store_half_rz","float.half / bits - overshoot correction / bitcast half",
    "720×1280×3→f16；reset先unitclamp，history保overshoot", " toward-zero half store，数值accepted reference",
    "多个half/f32/bit整数临时；视图不是物理kernel；FDP/native store候选尚未成为accepted", "O-base或O-blend","graph output/history",None,
    "原生rtz store可另验收；不得等同4060逐位刚需", "gap-post-fusion")

# Copies/views/controls outside matrix kernels.
ops("G-input","graph",M+"graph_front_v1.py","GraphFront.forward","entry.inputs[name].copy_(t) / graph.replay",
    "reset input42,516,480B；history input57,262,080B（metadata记录）", "纯copy+graph submission，非DPAS",
    "rgb/front/previous/rcp各copy到静态输入；图重放已开", "front/history","capture_body mainchain","bridge",
    "AMDgraph/reuse不等于本地尚未有graph；静态目的地可避免部分copy但新hooks全false", "already")
ops("G-output-pool","graph",M+"graph_front_v5.py","GraphFront._capture","output.copy_(temporary_result) inside captured graph",
    "720×1280×3 half5,529,600B", "纯copy，图输出pool-external存活", "临时body output→每图独立输出一读一写",
    "O-store","G-output-public","bridge","共享pool生命周期已处理；删copy须证明输出ownership", "gap-copy")
ops("G-output-public","graph",M+"graph_front_v1.py","GraphFront.forward","entry.output.clone()",
    "720×1280×3 half5,529,600B", "copy，不是view", "图持有output→caller-owned clone；避免下一replay覆写",
    "G-output-pool","H-commit / geometry composite","bridge","AMDpool内复用与caller生命周期不同，不能无证明返回旧buffer", "gap-copy")
ops("H-commit","history",B+"temporal.py","MotionNR.forward","result.detach().clone(); seed=(seed+1)&MASK32",
    "720×1280×3 half5,529,600B；13frame seed0…12", "clone纯copy；detach metadata；seedCPU",
    "再复制private previous，真实raw历史；没有host下载", "G-output-public","下一frame H-route / axes",None,
    "caller-output与history所有权不同；可比较双buffer，但不是采上帧少算", "gap-copy")
ops("E-composite","geometry","game/nr_game_fullsize.py","FrameGeometry.composite","processed.float().clamp(0,1)",
    "固定source720×1280=inputmodel，输出f32 HWC3", "convert +clamp标量", "同尺寸不Lanczos、不residual-upscale；half→float11,059,200B",
    "G-output-public","bridge.export",None,"固定720无降低画布收益；其他尺寸分支另列", "gap-copy")
ops("E-prepare","geometry","game/nr_game_fullsize.py","FrameGeometry.prepare","color/motion.float().contiguous() identity path",
    "source720×1280 HWC3/HWC2 f32，active=model720无inset", "metadata/no-op当输入dtype与layout满足",
    "不会宣称每个float/contiguous必起核；同shape直接传canvas/flow", "bridge.prepare","MotionNR/front",None,"该path非resizer，不能据源码_axis即算GPU resizer已跑")
ops("C-lanes","control","game/nr_game_controlled_model.py","GameLiveControlledNR.graph_controls","for lane10…14: front[...,lane]=control_lane",
    "front padded768×1280×16 half；controls style0/intensity1/local1", "标量fill；若native_controls_present有receipt则省写",
    "默认source能走五个lane fill；front_native kernel已写控制但producer receipt能力须看实际hook，不能假设全部消失",
    "F-front +NRControls","G-input",None,"保留控制；具体fill物理执行无receipt，列静态上界", "gap-control","static_path_no_individual_dispatch_receipt")
ops("C-default","control","game/nr_game_controlled_model.py","GameLiveControlledNR.forward","default controls→MotionNR.forward",
    "style0/intensity1/local1/auto_maskfalse，fixed13", "CPU分支/metadata；默认绕过style post",
    "不把loaded NativeStylePost权重当style shader已执行", "NRControls","H-route/front/body",None,
    "当前13帧仅默认控制；风格/lowstrength/aux全部未观测",kind="host_control")
ops("C-nondefault","control",B+"live_temporal.py","LiveControlledMotionNR.forward","Controlled/local/style/intensity/auto-mask/skin auxiliary routes",
    "720×1280；控制可变，强度<1 rawFP32图或eager", "条件标量/表/采样/FP32mix，完整帧",
    "非默认需clamp/skin/luma/style LUT及私人rawhistory；附录给每处AST调用点；不假定库物理核已审",
    "NRControls","controlled front/post/history",None,"fixed13 style1/2未执行，lowstrength须adapter harness；不用新GPU求100%",
    "already","conditional_unobserved")
ops("E-resize","geometry",M+"residual_scale_v1.py","_axis","residual_scale_v1._axis",
    "仅source≠model：Lanczos2 RGB、area motion×比例、Catmull residual；BLOCK256", "标量filter，无DPAS；shape动态",
    "每轴读写完整tensor；本次1280×720→1280×720没有此dispatch", "source/NR residual","model/bridge",None,
    "不得把输入下降/减少画布列为内核收益", "already","conditional_unobserved",kind="conditional_triton_kernel")

# Native model-external bridge references are separately pinned accepted sources.
def bridge_row(id, file, anchor, callable, shape, rw, producer, consumer, diff, root=None, line=None):
    root = root or BASE / "baseline/native"
    r = dict(id=id,stage="model-external bridge",kind="native_GPU_command_or_shader",
             local=reference(file,anchor,line,root),actual_callable=callable,
             shape_dtype_fullK=shape,arithmetic="D3D12 shader标量 / SYCL memcpy / GPU fence；无矩阵K",
             reads_writes_layout_temporaries=rw,producer=producer,consumer=consumer,
             amd=[A['bridge']],comparison=diff,improvement="already",
             evidence_class="accepted_bridge_source_only_not_offline_model_capture",
             evidence_gate=None,binding_symbol=None,binding_predicate={},sites=[],
             dynamic_dispatch_trace=False,physical_memory_traffic_measured=False)
    ROWS.append(r)
bridge_row("B-HDR-prepare","shaders/nr_hdr_proxy.hlsl","void prepare","prepare [numthreads(8,8,1)]",
    "R11G11B10 color / RG16F motion，1280×720", "写RGBA16/32 SDR代理及RG16 pixelmotion；motion scales/finite/clamp保留",
    "本帧游戏color/motion producer","RE8 pack","纹理复用/真实motion转换已存在，r18 audit native fastpack不计现役")
bridge_row("B-HDR-composite","shaders/nr_hdr_proxy.hlsl","void composite","composite [8,8,1]",
    "720×1280 scene/NR→R11G11B10 XeSSInput", "scene+highlights weight×(NR−SDR)，保原scene high values；逐pixel读写",
    "NR完成输出+原scene","XeSS input consumer","AMDregular pre-tonemap/HDR配方不同；不能删highlights保护")
for id,anchor,callable,shape,rw,prod,cons,diff in [
    ("B-pack","void pack(","embedded HLSL pack [8,8,1]","textures→USM-shared staging HWC3/HWC2 f32","各pixel颜色/运动→linear RGB/MV；中间stagebuffer",
     "HDR prepare+producer fence","B-copy-in","已验收pack；不是r18 new audit rawHDR候选"),
    ("B-unpack","void unpack(","embedded HLSL unpack [8,8,1]","linear result f32 HWC3→RGBA texture","读linear result写output texture",
     "B-copy-out / XPU completion","HDR composite","底层shader ISA未知，只有accepted source"),
    ("B-copy-in","void prepare_handoff(","prepare_handoff xpu->memcpy(color_ptr,rgb.ptr) + memcpy(motion_ptr,mv.ptr)","720×1280×(3+2)f32=18,432,000B",
     "共享staging到模型USM，两copies依赖forward import event","B-pack","E-prepare","GPU栅栏接力已开，不能计作新host同步消除收益"),
    ("B-copy-out","void export_handoff(","export_handoff xpu->memcpy(result.ptr,color)","720×1280×3 f32=11,059,200B",
     "模型USM→shared result，backward completion signal后D3D12 unpack","E-composite","B-unpack","异步export存活到consumer retirement，不能无证明消除copy"),
    ("B-fences","void prepare_handoff(","queue Wait producer →pack Signal →XPU external semaphore / backward Wait →unpack Signal",
     "每帧fence/value和retained imports","GPU queue依赖+ownership lease，serial model owner","游戏本帧producer","XPU model / game consumer",
     "与AMD hip_d3d12_bridge接口对应；现役已有relay，不用CPU_wait旧版作主对照"),
    ("B-retire","bool poll_handoff_idle(","consumer fence completion / lease retirement / command allocator reuse","上一borrowed output退休",
     "保texture/stagebuffer/command pool至真实consumer signal","XeSS consumer","next prepare reuse","不在offline capture；不能把source存在等同same-frame Present计时")]:
    bridge_row(id,BRIDGE.name,anchor,callable,shape,rw,prod,cons,diff,root=BRIDGE.parent)
bridge_row("B-pool","src/nr_hdr_proxy.cpp","void HdrProxy::bind","HdrProxy::bind/record_prepare/record_composite +resource pool",
    "width/height=format-scoped resources/PSO/root/descriptors", "Dispatch ceil(W/8)×ceil(H/8)，Barrier/ResourceState；cache复用",
    "game resources","HDR shaders","texture/resource复用已验收；不与r18 native protocol候选混算")

INSTALL_CHAIN = [
    ("game/nr_game_fullsize.py","FullsizeGameModes._select","constructor决定现役all6，height720，variant unrounded"),
    ("game/re4_session_v1.py","open_session","安装geometry720/internal768 contract"),
    ("game/fullsize_session_v1.py","FullsizeSession.__init__","rows_scopes全行FFN；覆盖SplitSwin/Vit.forward；排除graph/rewrite/call_guard/compact_queries旧小图"),
    ("game/rows_scopes_v1.py","install","实际FFN5/4核；不安装audit_impl"),
    ("game/three_structure_combo_v1.py","installed","C64/C128/C256 directpack，普通C32七tail，pre尾，C512 decoder projection"),
    ("game/post_attention_k8_combined_v1.py","installed","post entry→MLP→QKV→tail→croppedhead"),
    ("game/c512_k8_joint_scope_720_v1.py","installed","torch.mm all16 C512 +native pre/post K"),
    ("game/c32_hidden_native_720_v1.py","installed","pre/8C32/post native hidden"),
    ("game/c512_probability_unround_scope_v1.py","installed_720","all16 no probability FP8 simulation"),
    ("game/numeric_cleanup_suite_720_v1.py","installed","C128 native branch /fp32_fractional history/native_both front"),
    ("game/audit_history_host_720_v1.py","installed","before_numeric allfalse：准入/归属，未替换数学计算候选"),
    (M+"capture_body_v1.py","forward_front","完整71block源调用链；capture期间保替换作用域"),
    (M+"graph_front_v1.py","GraphFront.forward","2capture签名+11固定序列replay；Python计数不随图内物理派发重新递增"),
]

def binding_constants(v):
    names = list(v['signature'])
    return {names[e['key'][0]]:e['value'] for e in v['constants'] if len(e['key'])==1}

def local_call_ops(ref):
    """Exact syntactic callsites, not inferred physical ATen kernels."""
    if not ref['path'].endswith('.py'):
        return []
    content = text(ref['path']); tree = ast.parse(content)
    calls = []
    for n in ast.walk(tree):
        if isinstance(n,ast.Call) and ref['line']<=n.lineno<=ref['end_line']:
            name = ast.unparse(n.func)
            calls.append(dict(line=n.lineno,callee=name,expression=ast.get_source_segment(content,n),
                              execution="syntactic_only; branch_and_replacement_selection_required",
                              physical_kernel_count=None))
    return sorted(calls,key=lambda x:(x['line'],x['callee']))

def compiler_ir_proof(binding):
    proof=[]
    for name, expected in (binding.get('metadata_files') or {}).items():
        p=Path(name)
        if p.suffix not in ('.ttir','.ttgir'):
            continue
        if not p.exists():
            proof.append(dict(path=p.as_posix(),available=False,expected_sha256=expected))
            continue
        actual=digest(p)
        assert actual==expected, f'IR pin mismatch: {p}'
        lines=text(p).splitlines()
        hits=[dict(line=i+1,text=v) for i,v in enumerate(lines) if 'tt.dot' in v or '#ttig.dpas<' in v]
        proof.append(dict(path=p.as_posix(),available=True,sha256=actual,matched_expected_pin=True,
                          dot_and_layout_examples=hits[:4],has_DPAS_layout=any('#ttig.dpas<' in v for v in lines),
                          is_machine_ISA=False,evidence_class='pin_verified_compiled_IR_not_dispatch_trace'))
    return proof

def role_binding_filter(row, binding):
    # Shared callables serve several stages. Bind them only to compatible role shapes.
    allowed_m={'P-mlp':{983040},'S32-mlp':{245760,254016,248832,250880},
               'D32-mlp':{245760},'O-mlp':{999488}}
    if row['id'] in allowed_m and binding['constants'].get('M') not in allowed_m[row['id']]:
        return False
    return True

def make_porting(inv):
    template=text(OUT/'FULL_MODULE_PORTING.template.md')
    rows={r['id']:r for r in inv['rows']}
    import re
    def local(m):
        r=rows[m.group(1)]['local']
        return f"[{r['file']}:{r['line']} {r['symbol']}]({r['link']})"
    def upstream(m):
        file,line,label=m.group(1),int(m.group(2)),m.group(3)
        ref=reference(file,line=line,root=AMD)
        assert 1<=line<=len(text(AMD/file).splitlines())
        return f"[{label}（{file}:{line}）](https://github.com/lmxxf/dlss5-on-amd-9070xt-porting/blob/{AMD_SHA}/{file}#L{line})"
    def ir(m):
        r=rows[m.group(1)]
        for key in r['bound_specializations']:
            binding=next(b for b in inv['compiler_bindings'] if b['compiler_key']==key)
            for proof in binding['compiled_IR_proof']:
                if proof.get('available') and Path(proof['path']).suffix=='.'+m.group(2) and proof['dot_and_layout_examples']:
                    line=proof['dot_and_layout_examples'][0]['line']
                    return f"[{r['id']} pin校验 {m.group(2)}]({proof['path']}:{line})"
        raise ValueError(f'Missing requested IR {m.group(1)}:{m.group(2)}')
    rendered=re.sub(r'\[\[local:([^\]]+)\]\]',local,template)
    rendered=re.sub(r'\[\[amd:([^:]+):(\d+):([^\]]+)\]\]',upstream,rendered)
    rendered=re.sub(r'\[\[ir:([^:]+):(ttir|ttgir)\]\]',ir,rendered)
    assert '[[local:' not in rendered and '[[amd:' not in rendered and '[[ir:' not in rendered
    (OUT/'FULL_MODULE_PORTING.md').write_text(rendered,encoding='utf-8')

def extraction():
    assert OUT.name == 'kernel-by-kernel-v1'
    assert digest(MANIFEST)==EXPECTED_MANIFEST
    assert digest(RESULT)==EXPECTED_RESULT
    assert subprocess.check_output(['git','-C',str(AMD),'rev-parse','HEAD'],text=True).strip()==AMD_SHA
    manifest=read_json(MANIFEST); run=read_json(RESULT); scope=read_json(SCOPE)
    assert run['mode_options']==manifest['arms']['accepted_baseline']['constructor']
    r15=read_json(BASE/'phase2-complete/PHASE2-r15.json')
    assert r15['arms']['accepted_baseline']['constructor']==run['mode_options']
    assert run['workload']['height']==720 and run['workload']['width']==1280
    source_check=[]
    for e in manifest['source_files']:
        p=SOURCE/e['relative_path']; actual=digest(p)
        source_check.append(dict(relative_path=e['relative_path'],expected_sha256=e['sha256'],actual_sha256=actual,matched=actual==e['sha256']))
    assert all(e['matched'] for e in source_check)
    assert digest(BRIDGE)==read_json(BRIDGE_RECEIPT)['canonical_after_pins']['shared/native/nr_texture_bridge_re8_v1.cpp']
    assert digest(BRIDGE_RECEIPT)==scope['bridge_canonical_source_receipt']['sha256']
    bind=[]; by_hash={}
    for key,v in run['cache_gate']['actual_compiler_keys'].items():
        b=dict(compiler_key=key,source=v['source'],signature=v['signature'],constants=binding_constants(v),
               options={k:v['options'].get(k) for k in ['num_warps','num_stages','enable_fp_fusion','grf_mode']},
               loaded_kernel_hash=v.get('loaded_kernel_hash'),loaded_binary_sha256=v.get('loaded_binary_sha256'),
               metadata_files=v.get('metadata_files'),evidence_class='compiler_binding_only',matched_review_rows=[])
        assert digest(v['source']['path'])==v['source']['sha256']
        b['compiled_IR_proof']=compiler_ir_proof(b)
        bind.append(b);by_hash[key]=b
    gate=run['frames'][1]['combo_capture_gate']; fixed=run['fixed13_evidence']
    actual={}
    for name,data in fixed['numeric']['children'].items():
        actual[name]={k:data.get(k) for k in ['calls','capture_calls','eager_calls','actualkernelhash','actualkernelhash_by_site',
              'frame_route_calls','frontend_route_calls','launch_calls_by_specialization','launch_count_scope','body_graph_replays'] if k in data}
    for r in ROWS:
        r['bound_specializations']=[]
        if r['binding_symbol']:
            for b in bind:
                path=Path(b['source']['path']).as_posix()
                if path==r['local']['path'] and b['source']['qualname']==r['binding_symbol']:
                    if all(b['constants'].get(k)==v for k,v in r['binding_predicate'].items()) and role_binding_filter(r,b):
                        r['bound_specializations'].append(b['compiler_key']); b['matched_review_rows'].append(r['id'])
        r['runtime_evidence']={"gate_name":r['evidence_gate'],"gate_passed":gate.get(r['evidence_gate']) if r['evidence_gate'] else None,
                               "bound_specialization_count":len(r['bound_specializations']),
                               "individual_physical_dispatch_observed":False,
                               "capture_gate_is_provider_not_physical_kernel_list":True}
        if r['id'] in ('F-reset','F-history'):
            key='front.'+r['id'][2:];r['runtime_evidence'].update(calls=fixed['numeric']['children']['front']['calls'][key],
                actual_hash=fixed['numeric']['children']['front']['actualkernelhash'][key+'.seed_low'],scope='fixed13/outside_graph')
        elif r['id'] in ('H-axes','H-sample'):
            key='axes_fp32' if r['id']=='H-axes' else 'five_tap_debug_false'
            r['runtime_evidence'].update(calls=12,actual_hash=fixed['numeric']['children']['history']['actualkernelhash'][key],scope='fixed13/outside_graph')
        elif r['id']=='C128-mlpproject':
            r['runtime_evidence'].update(actual_hashes={k:v for k,v in actual['branch_accum']['actualkernelhash'].items() if k.endswith(':project')},
                capture_calls=actual['branch_accum']['capture_calls'],python_counts_exclude_replays=True)
        elif r['id']=='C128-pairs':
            r['runtime_evidence'].update(actual_hashes={k:v for k,v in actual['branch_accum']['actualkernelhash'].items() if k.endswith(':latent')},
                capture_calls=actual['branch_accum']['capture_calls'],python_counts_exclude_replays=True)
        if not r['amd']:
            r['amd_mapping_status']='no_equivalent_in_selected_regular_AMD_contract'
        else:r['amd_mapping_status']='fixed_source_function_mapping; not_same_hardware_or_recipe'
        r['compiled_IR_summary']=dict(
            bound_records_with_pinned_IR=sum(any(p.get('available') for p in by_hash[k]['compiled_IR_proof']) for k in r['bound_specializations']),
            bound_records_with_DPAS_layout=sum(any(p.get('has_DPAS_layout') for p in by_hash[k]['compiled_IR_proof']) for k in r['bound_specializations']),
            proof_scope='compiled specialization; not physical execution or machine ISA')
        r['priority_gain_evidence']=gain(r['improvement'])
        r['syntactic_calls']=local_call_ops(r['local'])
    allrefs={}
    for r in ROWS:
        allrefs[(r['local']['path'],r['local']['symbol'],r['local']['line'])]=r['local']
    chain=[dict(reference=reference(f,fn),selection=note) for f,fn,note in INSTALL_CHAIN]
    for c in chain:allrefs[(c['reference']['path'],c['reference']['symbol'],c['reference']['line'])]=c['reference']
    # Conditional control and near-history callees are expanded as syntactic ops.
    # No GPU calls, imports or reflection on live modules are performed here.
    extra_functions=[]
    for file in [B+'sampling.py',B+'style.py',B+'controlled_temporal.py',B+'local_temporal.py',B+'live_temporal.py',B+'intensity_temporal.py',
                 B+'styled_temporal.py',B+'exposure.py',B+'ui.py',B+'post.py',B+'reciprocal.py',M+'fast_matrices_v3.py',M+'strided_batched_v1.py',
                 M+'fused_c32_projection_native_half_v1.py',M+'native_cubic_c32_v1.py',M+'batched_branched_mlp_v1.py',
                 'game/history_numeric_suite_720_v1.py','game/front_noise_native_720_v1.py','game/nr_game_fullsize.py']:
        tree=ast.parse(text(SOURCE/file))
        def collect(node,prefix=''):
            for n in ast.iter_child_nodes(node):
                if isinstance(n,(ast.ClassDef,ast.FunctionDef,ast.AsyncFunctionDef)):
                    q=prefix+n.name
                    if isinstance(n,(ast.FunctionDef,ast.AsyncFunctionDef)) and not (n.name.startswith('from_') or n.name in ('__init__',)):
                        ref=reference(file,q)
                        extra_functions.append(dict(reference=ref,calls=local_call_ops(ref),
                            coverage='static_conditional_or_wrapper_expansion; includes unselected branches; not a physical execution list'))
                    collect(n,q+'.')
                else:collect(n,prefix)
        collect(tree)
    excluded=[]
    for p in sorted((SOURCE/'game').glob('audit_impl*.py')):
        tree=ast.parse(text(p)); js=[]
        for n in ast.walk(tree):
            if isinstance(n,ast.FunctionDef) and any('triton.jit' in ast.unparse(d) for d in n.decorator_list):js.append(dict(symbol=n.name,line=n.lineno))
        excluded.append(dict(path=p.as_posix(),sha256=digest(p),jit_definitions=js,
                              reason='accepted_baseline selects no audit_impl provider; loaded_modules/cache alone cannot include it'))
    excluded.extend([dict(name=n,reason=why) for n,why in [
        ('FusedVitQKV64','owned small-token forward_boundaries bypassed by FullsizeSession.vforward; no 240 fused kernel qualification'),
        ('C512 _groups','source exists but rows_scopes launches _expand and _reduce; not selected'),
        ('front.history_components','flag false and fixed13 calls0; preflight includes two seed variants'),
        ('history axes_fp16/debug_true','compiled-only spare variants; fixed13 motionfp32/debugfalse'),
        ('batched_branched_mlp C128 _project','binding exists but installed native _project_fp32 replaces it'),
        ('r18 K64/rowonce full/P4 audit FFN','candidate hooks excluded; do not count repairing r15 as current baseline gains'),
        ('AMD adaptive/skip/1088','outside full-frame full-K fixed720 comparison'),
        ('AMD legacy/optional kernel exports','mapping does not claim latest host selected every exported kernel')]])
    unique=sorted({(r['local']['path'],r['binding_symbol']) for r in ROWS if r['kind']=='triton_kernel' and r['binding_symbol']})
    inventory=dict(schema='accepted720-kernel-diff-v1',scope='accepted_baseline current720 C512+K8/all6, fullK/motion/history/control/13frames',
        fixed_sources=dict(AMD_head=AMD_SHA,manifest=dict(path=MANIFEST.as_posix(),sha256=EXPECTED_MANIFEST),
                           result=dict(path=RESULT.as_posix(),sha256=EXPECTED_RESULT),source_tree=SOURCE.as_posix()),
        mode_options=run['mode_options'],effective_numeric=run['numeric_options'],source_pin_verification=source_check,
        installation_chain=chain,main_block_sites=SITES,rows=ROWS,compiler_bindings=bind,
        actual_runtime_and_capture_receipts=actual,excluded_not_current=excluded,
        static_wrapper_and_conditional_calls=extra_functions,library_internal_GPU_kernels=None)
    unassigned=[b for b in bind if not b['matched_review_rows']]
    coverage=dict(schema='accepted720-kernel-coverage-v1',count_unit='review row = selected callable/producer-consumer role; not physical kernel launches',
        counts=dict(review_rows=len(ROWS),by_stage=dict(collections.Counter(r['stage'] for r in ROWS)),
                    by_kind=dict(collections.Counter(r['kind'] for r in ROWS)),
                    by_evidence=dict(collections.Counter(r['evidence_class'] for r in ROWS)),
                    distinct_static_current_triton_callable_definitions=len(unique),main_model_block_sites=len(SITES),
                    compiler_bindings=len(bind),bindings_associated_to_review_rows=len(bind)-len(unassigned),unassigned_bindings=len(unassigned),
                    verified_source_files=len(source_check),wrapper_or_conditional_function_expansions=len(extra_functions),
                    syntactic_calls_expanded=sum(len(x['calls']) for x in extra_functions),
                     compiler_bindings_with_pin_verified_IR=sum(any(p.get('available') for p in b['compiled_IR_proof']) for b in bind),
                     compiler_bindings_with_DPAS_IR_layout=sum(any(p.get('has_DPAS_layout') for p in b['compiled_IR_proof']) for b in bind),
                     individual_physical_dispatch_events_available=0,library_internal_kernels_verified=0),
        source_verification_is_not_execution_count=True,
        runtime=dict(fixed13_frames=len(run['frames']),routes=dict(collections.Counter(f['route'] for f in run['frames'])),
            fractional_history=12,near_integer_history=0,front_reset=1,front_history=12,
            fixed13_body_replay_counter=fixed['numeric']['children']['front']['body_graph_replays'],
            whole_process_graph_route_counts=run['graph_route_counts'],rawbody_events=run['workload']['raw_events'],
            combo_capture_gate=gate,conditional_coverage=run['conditional_coverage'],
            provider_status=fixed['provider_status'],cache_binding_count_only=run['cache_gate']['specialization_bindings']),
        unassigned_compiler_bindings=[dict(compiler_key=b['compiler_key'],source=b['source'],constants=b['constants'],evidence='binding_only_unobserved_or_spare') for b in unassigned],
        unknowns=[
            'No per-dispatch GPU trace in RESULT: capture provider gates plus source select kernels, not a physical launch census.',
            'torch.mm/ATen copy/pad/ALU/reduction internal GPU kernels, library algorithm/tile and ISA remain unknown.',
            'No per-kernel elapsed time / DRAM bytes / occupancy / spill-to-bandwidth relationship measured in this review.',
            'near-integer history, fp16-motion spare, high-seed, nondefault style/low-strength/auto-mask/skin paths not observed by fixed13.',
            'Default control-lane fills have source evidence; native producer receipt/fill physical counts not individually instrumented.',
            'External bridge source pins match accepted canonical receipt, but offline RESULT game_or_API_calls=false excludes bridge dispatch/Present.',
            'AMD fixed source mapping is analogous structure; no identical math/hardware work-equivalence or independent GPU reproduction.',
            'Conditional syntactic expansion includes inactive branches; does not promote every AST call to the active inventory.',
            'Pinned TTIR/TTGIR prove types and DPAS layouts for available compiled bindings; not physical dispatch or final machine ISA.'],
        acceptance='Complete explicitly selected main model call-chain static inventory plus declared conditional/interop/library boundaries; no claimed 100% dynamic coverage',
        validation=dict(manifest_hash=True,result_hash=True,r15_r18_constructor_identical=True,source_pins_all_match=True,
                        accepted_shared_native_cpp_pin_match=True,all_local_and_AMD_links_resolve=True,GPU_executed_by_extractor=False,
                        imported_project_modules=False,source_or_game_written=False,G_writes=False))
    write_json('KERNEL_INVENTORY.json',inventory)
    write_json('COVERAGE.json',coverage)
    make_markdown(inventory,coverage)
    return coverage

def gain(op):
    if op in {'N1','N2','N3','N4','N5','N6'}:
        budgets={'N1':(1,[0,.8]),'N2':(1,[0,1.5]),'N3':(1,[0,2.5]),'N4':(2,[0,.6]),'N5':(2,[0,.6]),'N6':(3,[0,.25])}
        pri,budget=budgets[op]
        return dict(plan=op,priority=pri,whole_module_budget_ms=budget,
            qualification='unmeasured estimate inherited from original PLAN; shared by all rows of module, not additive per row',
            minimum_Luna_experiment='one isolated whole-module swap on accepted baseline; same13 full frames/fullK/motion/history/controls; balanced A/B/B/A repeat; no GPU by this extractor')
    return dict(plan=op,priority=3 if op.startswith('gap-') else 0,whole_module_budget_ms=None,
        qualification='new gap unbudgeted; no measured gain assigned' if op.startswith('gap-') else 'already implemented or no current new gain',
        minimum_Luna_experiment='new gap: independent whole-frame isolated swap before assigning budget' if op.startswith('gap-') else None)

def make_markdown(inv,cov):
    counts=cov['counts']
    lines=['# accepted720 与 AMD：逐核及纯数据操作补审 v1','',
      '这份补审把现役主调用链拆到实际 callable、库 GEMM、纯数据/标量操作和模型外桥。AMD 作者归档约9.5～10ms网络成绩及结构分析沿用原报告；此处集中交付可实施的逐核差异。', '',
      f"主对照：r18 accepted_baseline，manifest `{EXPECTED_MANIFEST}`；r15/r18 constructor逐字段相同。固定1280×720，内部1280×768，C512有效24×40，ViT240 tokens。游戏现役用户RTSS55–60ms；未采用完整模块回退及r18 audit候选均排除。",'',
      f"AMD固定HEAD：`{AMD_SHA}`。本次重用已联网固定的源码；所有下列链接固定SHA，无新GPU运行。",'',
      f"库存共 **{counts['review_rows']}条角色行**，涉及 **{counts['distinct_static_current_triton_callable_definitions']}个当前静态Triton callable定义**、**71个模型块位点**。同核不同producer/consumer会重复列角色；不等于这个数量的物理launch。另存{counts['compiler_bindings']}个编译绑定，{counts['bindings_associated_to_review_rows']}个与角色关联，{counts['unassigned_bindings']}个单列未选/备选绑定。{counts['verified_source_files']}个源码SHA只用于来源校验。",'',
      '13帧只有两条捕获签名（首帧reset、随后history）、11次后续replay；front reset1/history12，fractional warp12/near0。图计数13包括捕获帧本身；whole-process78及rawbody50属于不同范围。captured_dispatch是逻辑旧算子计数，不是物理kernel trace。库内核、逐次物理派发与ISA覆盖率未被记录，不能写100%。', '',
      '读取说明：每个编号下第一表给实际接口/算量，第二表给布局/AMD对应/改造与证据。JSON保留每个编译key的完整signature/常量、源SHA、capture/runtime计数、pin校验的TTIR/TTGIR和AST调用点。无AMD同配方对应的时序/控制照样列出。', '',
      f"具体wave/fragment/load/store/live-range/prefetch/barrier/编译recipe及Intel SG16迁移伪代码见 [FULL_MODULE_PORTING.md]({(OUT/'FULL_MODULE_PORTING.md').as_posix()})。所有配方对照accepted callable；候选修复另列。",'',
      '快速版允许数值变化。N2先保持两个K512 QKV及P4 half投影仅为隔离结构收益；结构通过后可测full-K单累加、native norm/exponent/denominator。当前accepted这些开关仍false/reference；C128跨branch FP32已采纳。C512/ViT FFN已是i8矩阵→i32，不能重做“从FP16模拟改INT8”。不追加FP8模拟规则；四级Decoder merge已有输出lattice属于当前代码事实，去掉它是另一个未选fast候选。', '',
      '## 选择链与块位点','', '| 函数 | 实际选择 |','|---|---|']
    for c in inv['installation_chain']:
        r=c['reference'];lines.append(f"| [{r['symbol']}]({r['link']}) | {c['selection']} |")
    lines += ['', '块0 pre；1–4 C32、5–8 C64、9–14 C128、15–22 C256；23–30编码C512；31–38 ViT；39 decoder输入；40–47解码C512；48–55 C256、56–61 C128、62–65 C64、66–69 C32；70 post。每个具体形状/shift/up或down role保存在JSON `main_block_sites`。没有跳任何块。', '',
              '## 逐核差异','']
    last=None
    esc=lambda v:str(v).replace('|','／').replace('\n',' ')
    for r in inv['rows']:
        if r['stage']!=last:
            lines+=['',f"### {r['stage']}",''];last=r['stage']
        lr=r['local'];lines += [f"#### {r['id']} — `{r['actual_callable']}`",'',
          '| 项目 | 核查结果 |','|---|---|',
          f"| 现役入口 | [{esc(lr['file'])}:{lr['line']}]({lr['link']})；{r['kind']} |",
          f"| 配置、shape、dtype、full K | {esc(r['shape_dtype_fullK'])} |",
          f"| 运算/必要half边界 | {esc(r['arithmetic'])} |",
          f"| producer → consumer | {esc(r['producer'])} → {esc(r['consumer'])} |",
          f"| 读写、布局和临时 | {esc(r['reads_writes_layout_temporaries'])} |"]
        am='；'.join(f"[{esc(a['file'])}:{a['line']} {esc(a['symbol'])}]({a['url']})（{a['relation']}）" for a in r['amd']) or '无现役同配方AMD对应，明确未映射'
        lines += [f"| AMD 固定函数 | {am} |",f"| 差异/已实现 | {esc(r['comparison'])} |",
          f"| 改造优先级、收益证据 | {r['improvement']}；{esc(r['priority_gain_evidence']['qualification'])} |",
          f"| 覆盖证据/未知 | {r['evidence_class']}；关联{len(r['bound_specializations'])}个绑定（不自动当执行）；无逐物理dispatch轨迹 |",'']
        rr=r['runtime_evidence']
        if 'calls' in rr:lines +=[f"fixed13实际调用：{rr['calls']}；callee hash及binary见JSON runtime_evidence。",'']
        if rr.get('gate_name'):lines +=[f"捕获provider门：`{rr['gate_name']}`={rr['gate_passed']}。该门证明对应provider参与捕获；具体kernel为源码追溯，未声称library/ATen底层全部观察。",'']
        if r['priority_gain_evidence'].get('whole_module_budget_ms') is not None:
            lines += [f"{r['improvement']}整个方案沿用{r['priority_gain_evidence']['whole_module_budget_ms']}ms待证伪预算，不能逐行相加。修改入口即上方现役文件；最小Luna实验是只换此完整模块，在相同13帧上配平A/B/B/A，保留full K及真实时序控制。",'']
    lines += ['## 一对多结构、实施接口与新缺口','',
      '| AMD闭合单元 | 本地对应角色集合 | 实施边界及真实减少量 |','|---|---|',
      '| c5c_body 紧凑QKV→attention | C512-pad/QKV/pack/attn，以及encoder/decoder不同projection | N1先保持库GEMM在valid raster；19712→15360 QKV行，少4352行、3,422,552,064 MAC，约22.08% QKV算量；attention仍每窗64 keys。packed consumer保持fullkeys和bias/order。 |',
      '| vit_stream_qkv + fused attention | V-qkv/add/norm/Qscale/pad/QK/exp/AV/denom/final-div | N2 producer改head-major `[head,tile,64,32]`，consumer64key tile DPAS；初期保两个K512 half边界，score与exp各3,932,160B/块免落地，8块仅这两项写读少125,829,120B；padding和full240不削。该字节数是逻辑global张量容量，不是DRAM实测。 |',
      '| c32 wave整窗 cw_body | S32-pad/mlp/qkv/tail，block66还unpack/projection | N3一个window由工作组拥有，MLP/QKV/attention/tail依次局部消费；预留half residual/完整keys，滚动hidden16/32tile控SLM/GRF，先只ordinary7，再独立block66资格。现役tail已有fusion，只把MLP/QKV额外边界作新增。 |',
      '| mh QKV_FUSE | C64/C128-qkv | N4每head同tile共读A→Q/K/V三accumulator；输入请求3→1，布局仍packed，不删norm/keys。DPAS映射由Intel编译IR验证，不能照搬AMD warp寄存器排列。 |',
      '| mh QT4 FFN | C64/C128/C256-pairs/mlpproject | N5四token tile同组SLM共享W，逻辑W请求4→1；C128pairwise和FP32branch已开，改的是跨M复用。SLM/barrier与占用可能抵消收益。 |',
      '| sp_run_body C256依赖队列 | C256-pad/pairs/project/qkv/attn/project | N6完整多块逐window就绪依赖，图已重放；block-owned数据ready后消费，acquire/release fence及border窗口处理必须明确。不是单纯删Python launch。 |',
      '| decoder_project2x / wave up-body / post whole block | 五transition projection+gather、pool、post entry/body/head/temporal/store | 新缺口不并入N1–N6预算：投影与nearest/skip融合、pool就地project、post完整真历史epilogue。FDP已重复1.80ms是另候选完整帧结果，未装游戏；不能拆给各行或加到六方案。 |','',
      '后续fast数学候选：现有decoder_input_full_k、vit_qkv_full_k、vit_projection_full_k、vit_norm_fma、vit_exp_fma、vit_denominator与post_sigmoid/store等已在numeric_cleanup中有实现/选择器，但本accepted未收；本次不重新开发、不重新追加舍入。跨完整K的一次FP32/i32累积仍是full K，允许按误差/视觉/可重复完整帧收益验收。', '',
      '## 绑定备选、排除项与盲区','',
      '139个cache key只证明编译/绑定：例如C128旧project、history debug、front components/high-seed等可以被预编译却没在固定13帧执行。JSON把未关联项逐条保留；loaded_modules不作为运行门。当前audit_history_host全false只作准入；所有audit_impl新核均在excluded_not_current列出。', '',
      '源代码的零spill选择门仍在：rows_scopes.launch调用spill_preflight.select，C32 native preflight调用筛选。它约束可选tile，却不证明保留tile最快，也不把spill等同慢根因。逐位/ordered-half来自原accepted实现；快速新方案允许数值变化，不是4060永久刚需。本补审没有新单核计时或删门收益可宣称。', '',
      '模型外桥以PHASE1指向RUNTIME_SCOPE和已验收canonical收据为来源，shared native C++ SHA匹配e45f5af…；离线RESULT没有game/API调用，不能拿它证明桥派发/渲染重叠/Present。ATen/torch.mm内部库kernel和ISA、逐次copy的kernel合并/调度、硬件内存流量仍未知。', '',
      '近整数motion、非默认style/lowstrength/auto-mask/skin、其他source尺寸只完成静态条件库存。附录JSON `static_wrapper_and_conditional_calls`给逐调用点/表达式和行号，但它包括未选分支；不能伪装动态执行清单。当前主链所有静态role均列入，上述边界明确保留，无另跑GPU。', '',
      '## 复算','',
      '`extract_inventory.py`只用stdlib AST/JSON/hash，读取固定r18/RESULT/AMD及accepted桥收据，验证SHA与constructor，重建三份输出。用bundled Python加`-B`运行，禁止导入项目torch/Triton；所有输出限定本目录。手写结构映射是review annotation，AST不能自行推导monkey patch的最终选择。', '',
      f"验证：{counts['verified_source_files']}个r18 source pins匹配，manifest/RESULT SHA正确，r15/r18 constructor同，AMD HEAD固定，所有函数/行链接解析通过。物理event覆盖数0，库内部已核数0；这两项明确留空。",'']
    (OUT/'KERNEL_DIFF.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')

if __name__=='__main__':
    result=extraction()
    print(json.dumps(dict(counts=result['counts'],validation=result['validation']),ensure_ascii=False))
